driver:
  name: docker
  use_sudo: false

platforms:
  - name: debian-7

<% %w(12.04 14.04).each do |ubver| %>
  - name: ubuntu-<%= ubver %>
    driver:
      platform: ubuntu
      # Testing starting/stopping services inside a container needs an init
      image: ubuntu-upstart:<%= ubver %>
      disable_upstart: false
      run_command: /sbin/init
<% end %>

  # @todo figure out how to test systemd in docker
  # - name: ubuntu-15.04
  #   driver:
  #     run_command: /lib/systemd/systemd
