language: ruby
cache: bundler
sudo: false

rvm:
  - 2.0
  - 2.1
  - 2.2

bundler_args: --without development kitchen_docker kitchen_vagrant

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/3ba4761e5efe291965bf
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
