name 'es-elk'
maintainer 'Maz'
maintainer_email 'mazharul@seekasia.com'
license 'all_rights'
description 'Installs/Configures es-elk'
long_description 'Installs/Configures es-elk'
version '0.1.0'

depends 'elasticsearch', '>= 2.1.1'
depends 'nginx'
depends 'kibana'
